# Generated by Django 2.1.7 on 2019-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
