# Generated by Django 2.1.7 on 2019-04-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ytburl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=100),
        ),
    ]
